### ISSUE TITLE
Is this correct?  The Japanese seems much shorter than the english. Just want to double check.

### ISSUE THREAD

**Issue by iamwillow** [tacoo/working2live_living2work#3]
How many moments have you lost thinking about the next one? Thinking that once you get this or get there that maybe that will be the best one.

何をどうすれば最適か考えることに、どれだけの時間を失ったでしょうか。

**Comment by tacoo** [comment]
次の一歩を踏み出すのにどれだけの時間を失ったでしょうか。あれこれ考えてベストになるように考え過ぎていませんか。

**Comment by tacoo** [comment]
hmm wait a sec
