### ISSUE TITLE
How about this?

### ISSUE THREAD

**Issue by iamwillow** [tacoo/working2live_living2work#5]
Is it ok to change this:
パームパイロット（小型端末）ではなく、パームツリー（ヤシの木）に。

with this?
携帯電ではなく、ヤシの木に。

( The text is fast, I'm afraid the user will not be able to read the long sentence.)

**Comment by tacoo** [comment]
in this case, it means 'palm trees instead of mobile phone'. a bit hard to understand what they wanted to say.

**Comment by iamwillow** [comment]
Yea, that sounds odd.  But there is a small visual of a phone becoming a palm tree. 

Can we same something closer to "replace your view of your cell phone with a view of palm trees?"
That might make more sense.

**Comment by iamwillow** [comment]
Or more.. "View of your palm trees instead of view of cell phone."

**Comment by tacoo** [comment]
looks good to you?

**Comment by iamwillow** [comment]
:+1:  Looks good to me.  Does it make sense?

**Comment by tacoo** [comment]
[![LGTM](http://www.lgtm.in/p/qNyH4eZMs)](http://www.lgtm.in/i/qNyH4eZMs)
